-- ============================================
-- ChainSpace 内置镜像初始化
-- 说明：
-- 1. 本脚本将平台内置镜像元数据导入 docker_images 表。
-- 2. 镜像名称与标签优先对齐本机 Docker / K8s 当前可直接使用的镜像引用：
--    chainspace/<image>:latest
-- 3. 描述、分类、特性与基础镜像来源于平台镜像清单 deploy/images/versions.yaml。
-- ============================================

INSERT INTO docker_images (
    name,
    tag,
    registry,
    description,
    category,
    default_resources,
    features,
    env_vars,
    ports,
    base_image,
    size,
    status,
    is_built_in
) VALUES
(
    'chainspace/base',
    'latest',
    NULL,
    '平台基础开发镜像，提供常用系统工具和统一运行基础。',
    'base',
    '{"cpu": 1, "memory": "2Gi", "storage": "10Gi"}'::jsonb,
    '["Ubuntu 22.04", "基础系统工具", "统一构建基础"]'::jsonb,
    '{}'::jsonb,
    '[]'::jsonb,
    'ubuntu:22.04',
    0,
    'active',
    TRUE
),
(
    'chainspace/dev-node',
    'latest',
    NULL,
    'Node.js 开发环境，适用于前端、脚本与 DApp 配套开发。',
    'base',
    '{"cpu": 2, "memory": "4Gi", "storage": "20Gi"}'::jsonb,
    '["Node.js 20", "前端开发", "脚本运行"]'::jsonb,
    '{}'::jsonb,
    '[]'::jsonb,
    'chainspace/base:latest',
    0,
    'active',
    TRUE
),
(
    'chainspace/dev-go',
    'latest',
    NULL,
    'Go 开发环境，适用于链码、后端服务与工具开发。',
    'base',
    '{"cpu": 2, "memory": "4Gi", "storage": "20Gi"}'::jsonb,
    '["Go 1.21", "服务开发", "命令行工具"]'::jsonb,
    '{}'::jsonb,
    '[]'::jsonb,
    'chainspace/base:latest',
    0,
    'active',
    TRUE
),
(
    'chainspace/dev-rust',
    'latest',
    NULL,
    'Rust 开发环境，适用于 Solana、Substrate 与 Move 生态实验。',
    'base',
    '{"cpu": 2, "memory": "4Gi", "storage": "20Gi"}'::jsonb,
    '["Rust stable", "Cargo", "区块链 Rust 生态"]'::jsonb,
    '{}'::jsonb,
    '[]'::jsonb,
    'chainspace/base:latest',
    0,
    'active',
    TRUE
),
(
    'chainspace/dev-python',
    'latest',
    NULL,
    'Python 开发环境，适用于安全分析、数据分析与脚本实验。',
    'base',
    '{"cpu": 2, "memory": "4Gi", "storage": "20Gi"}'::jsonb,
    '["Python 3.11", "脚本分析", "实验工具链"]'::jsonb,
    '{}'::jsonb,
    '[]'::jsonb,
    'chainspace/base:latest',
    0,
    'active',
    TRUE
),
(
    'chainspace/eth-dev',
    'latest',
    NULL,
    '以太坊智能合约开发环境，适用于 Solidity、Foundry 与 Hardhat 实验。',
    'ethereum',
    '{"cpu": 2, "memory": "4Gi", "storage": "20Gi"}'::jsonb,
    '["Solidity 0.8.24", "Foundry", "Hardhat"]'::jsonb,
    '{"CHAIN_ENV": "ethereum"}'::jsonb,
    '[8545, 8546]'::jsonb,
    'chainspace/dev-node:latest',
    0,
    'active',
    TRUE
),
(
    'chainspace/geth',
    'latest',
    NULL,
    'Geth 以太坊节点镜像，适用于链节点、RPC 与多节点组网实验。',
    'ethereum',
    '{"cpu": 2, "memory": "4Gi", "storage": "40Gi"}'::jsonb,
    '["Geth 1.13.14", "Ethereum RPC", "链节点服务"]'::jsonb,
    '{"CHAIN_ENV": "ethereum"}'::jsonb,
    '[8545, 8546, 30303]'::jsonb,
    'chainspace/base:latest',
    0,
    'active',
    TRUE
),
(
    'chainspace/dapp-dev',
    'latest',
    NULL,
    '全栈 DApp 开发环境，适用于合约、前端与交互式应用开发。',
    'ethereum',
    '{"cpu": 2, "memory": "4Gi", "storage": "20Gi"}'::jsonb,
    '["全栈 DApp", "前后端联调", "Web3 集成"]'::jsonb,
    '{"CHAIN_ENV": "ethereum"}'::jsonb,
    '[3000, 5173]'::jsonb,
    'chainspace/eth-dev:latest',
    0,
    'active',
    TRUE
),
(
    'chainspace/bitcoin',
    'latest',
    NULL,
    'Bitcoin Core 节点环境，适用于比特币协议与 UTXO 实验。',
    'bitcoin',
    '{"cpu": 2, "memory": "4Gi", "storage": "40Gi"}'::jsonb,
    '["Bitcoin Core 26.0", "UTXO 模型", "比特币节点"]'::jsonb,
    '{"CHAIN_ENV": "bitcoin"}'::jsonb,
    '[8332, 8333]'::jsonb,
    'chainspace/base:latest',
    0,
    'active',
    TRUE
),
(
    'chainspace/solana',
    'latest',
    NULL,
    'Solana 程序开发环境，适用于 Anchor 与链上程序实验。',
    'solana',
    '{"cpu": 2, "memory": "4Gi", "storage": "20Gi"}'::jsonb,
    '["Solana 1.18.4", "Anchor", "程序开发"]'::jsonb,
    '{"CHAIN_ENV": "solana"}'::jsonb,
    '[8899, 8900]'::jsonb,
    'chainspace/dev-rust:latest',
    0,
    'active',
    TRUE
),
(
    'chainspace/substrate',
    'latest',
    NULL,
    'Substrate / Polkadot 开发环境，适用于运行时与链开发实验。',
    'substrate',
    '{"cpu": 2, "memory": "4Gi", "storage": "20Gi"}'::jsonb,
    '["Substrate", "Polkadot", "Rust 链开发"]'::jsonb,
    '{"CHAIN_ENV": "substrate"}'::jsonb,
    '[9944, 9933]'::jsonb,
    'chainspace/dev-rust:latest',
    0,
    'active',
    TRUE
),
(
    'chainspace/cosmos',
    'latest',
    NULL,
    'Cosmos SDK 开发环境，适用于模块链与跨链协议实验。',
    'cosmos',
    '{"cpu": 2, "memory": "4Gi", "storage": "20Gi"}'::jsonb,
    '["Cosmos SDK 0.50", "模块化链", "Go 生态"]'::jsonb,
    '{"CHAIN_ENV": "cosmos"}'::jsonb,
    '[26656, 26657]'::jsonb,
    'chainspace/dev-go:latest',
    0,
    'active',
    TRUE
),
(
    'chainspace/move',
    'latest',
    NULL,
    'Move 语言开发环境，适用于 Aptos / Sui 方向实验。',
    'move',
    '{"cpu": 2, "memory": "4Gi", "storage": "20Gi"}'::jsonb,
    '["Move", "Aptos", "Sui"]'::jsonb,
    '{"CHAIN_ENV": "move"}'::jsonb,
    '[]'::jsonb,
    'chainspace/dev-rust:latest',
    0,
    'active',
    TRUE
),
(
    'chainspace/l2-dev',
    'latest',
    NULL,
    'Layer2 Rollup 开发环境，适用于二层扩容与 Rollup 机制实验。',
    'l2_privacy',
    '{"cpu": 2, "memory": "4Gi", "storage": "20Gi"}'::jsonb,
    '["Layer2", "Rollup", "扩容机制"]'::jsonb,
    '{"CHAIN_ENV": "l2"}'::jsonb,
    '[8545, 8546]'::jsonb,
    'chainspace/eth-dev:latest',
    0,
    'active',
    TRUE
),
(
    'chainspace/privacy',
    'latest',
    NULL,
    '隐私与零知识开发环境，适用于 ZK、Circom 与隐私协议实验。',
    'l2_privacy',
    '{"cpu": 2, "memory": "4Gi", "storage": "20Gi"}'::jsonb,
    '["ZK", "Circom", "SnarkJS"]'::jsonb,
    '{"CHAIN_ENV": "privacy"}'::jsonb,
    '[]'::jsonb,
    'chainspace/dev-rust:latest',
    0,
    'active',
    TRUE
),
(
    'chainspace/fabric',
    'latest',
    NULL,
    'Hyperledger Fabric 开发环境，适用于联盟链与链码实验。',
    'fabric',
    '{"cpu": 2, "memory": "4Gi", "storage": "30Gi"}'::jsonb,
    '["Fabric 2.5.4", "Fabric CA", "联盟链开发"]'::jsonb,
    '{"CHAIN_ENV": "fabric"}'::jsonb,
    '[7050, 7051, 7054]'::jsonb,
    'chainspace/dev-go:latest',
    0,
    'active',
    TRUE
),
(
    'chainspace/fisco',
    'latest',
    NULL,
    'FISCO BCOS 开发环境，适用于政企链与联盟链实验。',
    'fisco',
    '{"cpu": 2, "memory": "4Gi", "storage": "30Gi"}'::jsonb,
    '["FISCO BCOS 3.6.0", "联盟链", "企业场景"]'::jsonb,
    '{"CHAIN_ENV": "fisco"}'::jsonb,
    '[8545, 30300]'::jsonb,
    'chainspace/dev-node:latest',
    0,
    'active',
    TRUE
),
(
    'chainspace/chainmaker',
    'latest',
    NULL,
    'ChainMaker 开发环境，适用于国产联盟链教学实验。',
    'chainmaker',
    '{"cpu": 2, "memory": "4Gi", "storage": "30Gi"}'::jsonb,
    '["ChainMaker 2.3.2", "联盟链", "国产链实验"]'::jsonb,
    '{"CHAIN_ENV": "chainmaker"}'::jsonb,
    '[12301, 12302]'::jsonb,
    'chainspace/dev-go:latest',
    0,
    'active',
    TRUE
),
(
    'chainspace/ipfs',
    'latest',
    NULL,
    'IPFS 节点镜像，适用于去中心化存储与内容寻址实验。',
    'infrastructure',
    '{"cpu": 1, "memory": "2Gi", "storage": "20Gi"}'::jsonb,
    '["IPFS 0.27.0", "去中心化存储", "内容寻址"]'::jsonb,
    '{}'::jsonb,
    '[4001, 5001, 8080]'::jsonb,
    'chainspace/dev-node:latest',
    0,
    'active',
    TRUE
),
(
    'chainspace/blockscout',
    'latest',
    NULL,
    'Blockscout 区块浏览器镜像，适用于链上交易与状态观测。',
    'infrastructure',
    '{"cpu": 2, "memory": "4Gi", "storage": "20Gi"}'::jsonb,
    '["Blockscout 6.3.0", "区块浏览器", "链上观测"]'::jsonb,
    '{}'::jsonb,
    '[4000]'::jsonb,
    'blockscout/blockscout-staging:latest',
    0,
    'active',
    TRUE
),
(
    'chainspace/thegraph',
    'latest',
    NULL,
    'The Graph 索引服务镜像，适用于子图索引与链上数据查询实验。',
    'infrastructure',
    '{"cpu": 2, "memory": "4Gi", "storage": "20Gi"}'::jsonb,
    '["The Graph", "子图索引", "链上数据查询"]'::jsonb,
    '{}'::jsonb,
    '[8000, 8020, 8030, 8040]'::jsonb,
    'graphprotocol/graph-node:v0.41.1',
    0,
    'active',
    TRUE
),
(
    'chainspace/chainlink',
    'latest',
    NULL,
    'Chainlink 预言机节点镜像，适用于预言机与链下数据实验。',
    'infrastructure',
    '{"cpu": 2, "memory": "4Gi", "storage": "20Gi"}'::jsonb,
    '["Chainlink 2.9.1", "预言机", "链下数据接入"]'::jsonb,
    '{}'::jsonb,
    '[6688]'::jsonb,
    'smartcontract/chainlink:2.9.1',
    0,
    'active',
    TRUE
),
(
    'chainspace/simulation',
    'latest',
    NULL,
    '可视化仿真引擎，适用于交互式实验、可视化沙箱与机制演示。',
    'simulation',
    '{"cpu": 2, "memory": "4Gi", "storage": "20Gi"}'::jsonb,
    '["可视化仿真", "交互式实验", "机制演示"]'::jsonb,
    '{}'::jsonb,
    '[3000, 8080]'::jsonb,
    'debian:bookworm-slim',
    0,
    'active',
    TRUE
),
(
    'chainspace/security',
    'latest',
    NULL,
    '智能合约安全审计环境，适用于 Slither、Mythril 与 Echidna 实验。',
    'security',
    '{"cpu": 2, "memory": "4Gi", "storage": "20Gi"}'::jsonb,
    '["Slither", "Mythril", "Echidna"]'::jsonb,
    '{}'::jsonb,
    '[]'::jsonb,
    'chainspace/dev-python:latest',
    0,
    'active',
    TRUE
),
(
    'chainspace/crypto',
    'latest',
    NULL,
    '密码学实验环境，适用于哈希、签名、加密与协议实现教学。',
    'security',
    '{"cpu": 2, "memory": "4Gi", "storage": "20Gi"}'::jsonb,
    '["密码学算法", "协议实验", "Python 工具链"]'::jsonb,
    '{}'::jsonb,
    '[]'::jsonb,
    'chainspace/dev-python:latest',
    0,
    'active',
    TRUE
)
ON CONFLICT (name) DO UPDATE SET
    tag = EXCLUDED.tag,
    registry = EXCLUDED.registry,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    default_resources = EXCLUDED.default_resources,
    features = EXCLUDED.features,
    env_vars = EXCLUDED.env_vars,
    ports = EXCLUDED.ports,
    base_image = EXCLUDED.base_image,
    size = EXCLUDED.size,
    status = EXCLUDED.status,
    is_built_in = EXCLUDED.is_built_in,
    updated_at = CURRENT_TIMESTAMP,
    deleted_at = NULL;

DO $$
BEGIN
    RAISE NOTICE 'ChainSpace 内置镜像初始化完成，共同步 % 条镜像记录。', (
        SELECT COUNT(*) FROM docker_images WHERE is_built_in = TRUE AND deleted_at IS NULL
    );
END $$;
